name: SAP OpenClient

on:
 push:
  paths:
    - 'sap-ocs/**'
    - 'test/**'
    - '.github/workflows/sap-ocs_client.yaml'
  pull_request:
    paths:
    - 'sap-ocs/**'
    - 'test/**'
    - '.github/workflows/sap-ocs_client.yaml'

env:
  IMAGE: "docker.io/sqlops/sybase-ocs"
  DOCKERFILE: "./sap-ocs/Dockerfile.ci"
  ENV_FILE: "./sap-ocs/.env"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: Set ENV variables
        run: |
          cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Build & Push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMAGE }}:${{ env.SEMVER_MAJOR }},${{ env.IMAGE }}:${{ env.SEMVER_MINOR }},${{ env.IMAGE }}:${{ env.SEMVER_PATCH }},${{ env.IMAGE }}:${{ env.SEMVER_TAG }},${{ env.IMAGE }}:latest
          context: ./
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64
          push: True
